### ISSUE TITLE
ci: Switch to `radicle-services` infra

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/infra#143]
The `opensourcecoin` project on GCP that we use to store build artifacts and container images for Buildkite CI will be shut down soon. Infrastructure will be provided by the `radicle-services` project which is managed by @adaszko.

The new infrastructure consist of a build artifacts storage bucket, container registry, and a service account with write access to these resources.

To migrate our Buildkite agent we need to do the following

* Ask @adaszko to give access to the new resources for the current service accounts (`buildkite-agent@opensourcecoin.iam.gserviceaccount.com` and `buildkite-mac-n-cheese@opensourcecoin.iam.gserviceaccount.com`)
* Change the build artifact bucket from `builds.radicle.xyz` to `builds-prime.radicle.xyz`.
* Add `gcr.io/radicle-services` to the container registry allow list. (Grep for `gcr.io/opensourcecoin` to find the allow list)
* Update docker image URLs in the projects we build so they point to `gcr.io/radicle-services`. It is possible that some images need to be rebuild by CI. This would also require updating the tags for the images. (See [“Building Docker Images”](https://github.com/radicle-dev/infra/tree/master/ci#building-docker-images).)
* Obtain service account credentials (a JSON key file) from @adaszko and put them on our agent in `/etc/gce/cred.json`

## Individual image hosting

In the past developers have occasionally built images locally and pushed them to the container registry. This required write access to the container registry for the developer accounts which we don’t have anymore.

If the teams want to continue to build and push images locally they should use their own container image hosting service and add it to the allow list for images.

**Comment by kim** [comment]
Tbh, this seems like quite avoidable churn. I'm wondering:

- who is responsible for making these changes?
- what is the SLA for the `radicle-services` infra?

>      * Ask ***@***.*** to give access to the new resources for the current
>        service accounts
>        ***@***.*** and
>        ***@***.***)

Do service accounts survive projects?

**Comment by geigerzaehler** [comment]
> Tbh, this seems like quite avoidable churn

If you somebody convinces the foundation to keep the old project around or if anybody knows an easier way to migrate feel free to mention it.

> - who is responsible for making these changes?

I can volunteer for making these changes but only after 20 September.

> - what is the SLA for the `radicle-services` infra?

There’s nothing formalized. I just informed them that we need the bucket, container registry and service account to continue running buildkite.

> Do service accounts survive projects?

I don’t know but I don’t think so. The idea is to give the old service account access to the new infra temporarily so that we can make the changes with little down time as possible. Finally, we can switch to a service account from the new project and delete the old project and service account.

**Comment by kim** [comment]
>    If you somebody convinces the foundation to keep the old project around
>    or if anybody knows an easier way to migrate feel free to mention it.

Well, this could've been achieved without disruption if it wasn't for the name
change. Since "opensourcecoin" is deprecated since a long time, the necessity
escapes me.

It might be a good idea to avoid this kind of thing in the future by hiding GCP
details behind DNS names. This may entail proxying the container registry[0].

>      * what is the SLA for the radicle-services infra?
>
>    Thereâs nothing formalized. I just informed them that we need the
>    bucket, container registry and service account to continue running
>    buildkite.

I take this as a "none".

It probably doesn't make sense for link to rely on this anymore at this point.


[0]: https://cloud.google.com/blog/topics/developers-practitioners/hack-your-own-custom-domains-container-registry

**Comment by adaszko** [comment]
> Do service accounts survive projects?

They don't, but there are ways of granting cross-project permissions to service account which makes it possible to migrate between projects more smoothly.

> It might be a good idea to avoid this kind of thing in the future by hiding GCP details behind DNS names. This may entail proxying the container registry[0].

I'm happy to look into setting up such a proxy.  Let's just clearly agree on a course of action we're taking first :)

> * what is the SLA for the radicle-services infra?

Of the services that BuildKite uses, the SLA is as a good as GCP's itself basically.  The reason being BuildKite relies directly on (1) a Cloud Storage bucket (2) the Container Registry.  There are no layers or any custom services of ours that could lessen those SLAs.

**Comment by adaszko** [comment]
It has been decided to phase out BuildKite altogether so the migration work is no longer necessary.
