### ISSUE TITLE
Prune images built by steps

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/infra#40]
We’re not removing images built by a step when `STEP_DOCKER_FILE` is set. We should extend the `docker-volume-prune` service to also remove these images.

**Comment by kim** [comment]
You mean the cache volume for `img`, or the images themselves? I haven't thought about image GCing at all, because I'm not sure how to determine if an image is no longer in use. We could just prune all the images every month or so, and pay the miniscule price of pulling them again where needed.

**Comment by geigerzaehler** [comment]
I mean the images themselves, not the cache volumes. It is probably hard to determine which images where build locally so removing all images should be ok.

**Comment by FintanH** [comment]
_Hypothetically_, if I wanted to take this task on... The idea is to GC all the images on, say, the 1st of the month via this [script](https://github.com/radicle-dev/infra/blob/master/ci/linux/etc/systemd/system/docker-volume-prune.sh)?

**Comment by kim** [comment]
Yeah, although this imaginary script would be a lot simpler -- just
something like `docker rmi $(docker images --format='{{.ID}}')` + a
systemd timer

**Comment by kim** [comment]
It turns out that `docker-system-prune` actually works fine
