### ISSUE TITLE
Integrate registry infrastructure code

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/infra#68]
The terraform code for the registry development infrastructure lives in a private repo at the moment. It should be moved here. We should carefully review the repo to not expose sensitive data.

**Comment by geigerzaehler** [comment]
@kim: My plan is to just create a PR that adds all the code in the `registry` folder. There are no issues on the repo that we need to transfer. Is there anything else that I have to consider?

**Comment by kim** [comment]
@geigerzaehler Sounds good. Feel free to add a .sops.yaml (I believe this needs
to go at the top level).
