### ISSUE TITLE
Improve continuous deployment for registry nodes

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/infra#79]
To run and test the latest registry nodes we are currently updating the node version on the devnet for every master build of the registry. This is implemented through a build step that sends an update to the Kubernetes cluster with `kubectl`. There are two issues with this approach
* The build agent needs credentials with permission to update the image. This is a security risk
* The build step in the registry repo needs to be aligned with the cluster setup here. I.e. if we add a deployment of nodes we also need to update the deployment code in the registry repo.

To address this issue I propose we move the deployment logic to the devnet cluster. Concretely we run a Kubernetes service or job that updates the image when a new master build is available. I’m not aware of a simple tool that allows us to do that. I’d propose implementing a simple Kubernetes job that pulls the git repository and updates the images when a new commit is available.

**Comment by kim** [comment]
How about running a buildkite agent inside the cluster? The agent container doesn't need the custom hooks we have for CI, except for rejecting any jobs which don't originate from the registry repo / it's master branch. There are "official" docker images available, you'd only need to add `kubectl` (and perhaps `terraform`).

A deployment could then be [triggered](https://buildkite.com/docs/pipelines/trigger-step) from the repo pipeline.

**Comment by geigerzaehler** [comment]
> How about running a buildkite agent inside the cluster?

Interesting idea. This might be beneficial beyond this narrow use case. I’ll take a look and see how difficult it is to implement this with buildkite.
