### ISSUE TITLE
Use tag names to easily identify build artifacts

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/infra#89]
To make it easier for developers and users to identify and reference artifacts (both binaries and docker images) I propose we use tag names to identify them when tags are built.

If a tag `foo` is build the docker image should be tagged `${STEP_DOCKER_IMAGE}:${BUILDKITE_TAG}`. Similarly artifacts should be published to `gs://builds.radicle.xyz/${BUILDKITE_PIPELINE_SLUG}/tags/${BUILDKITE_TAG}`.

**Comment by kim** [comment]
Sounds good to me.
