### ISSUE TITLE
Alert when blocks are mined too quickly

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/infra#93]
This should be monitored the same as mining too slow, except it should trigger only if `is_major_synced` is set. The margin of error should be smaller for averages over larger time windows.

**Comment by geigerzaehler** [comment]
We’re seeing false positives for this when miners are restarted and sync very quickly. We’re not using `substrate_sub_libp2p_is_major_syncing` correctly. If this metric goes to 0 we still have a high import rate for some time. Maybe we need to consider using the `substrate_block_height{status="sync_target"}`

**Comment by CodeSandwich** [comment]
This is going to be tricky. I agree that `substrate_sub_libp2p_is_major_syncing` isn't the right gauge to look at, it's `1` only when there's really a lot to import.

The `sync_target` is going to be rather tricky. AFAIK it's different from `best` whenever there's anything to sync, so there's no clear way to tell being bootstrapped from bigger regular syncing.

Maybe we should look at the block timestamps? We could attach the [Prometheus timestamp](https://prometheus.io/docs/prometheus/latest/querying/functions/#timestamp) to every data point. If in the window any of the block timestamps is older than the Prometheus timestamp by more than let's say 10 minutes, the whole window is considered to be witnessing some serious syncing and not eligible for raising an alert.

**Comment by geigerzaehler** [comment]
How about not alerting on a high block import rate for the stateless nodes (i.e. the miner and the rpc server)? This would solve the problem and I cannot think of a case where there is something wrong and the block rate is high on stateless nodes but not on the stateful validators.

**Comment by CodeSandwich** [comment]
That's a very reasonable life simplification. The only case when we may keep getting spam will be during restarting of the validator nodes, but that's rare and we'll be expecting that.

**Comment by geigerzaehler** [comment]
> The only case when we may keep getting spam will be during restarting of the validator nodes

Since the validator nodes are stateful they will not sync extensively. The will start from the chain they shut down with.
