### ISSUE TITLE
Fix nodes being mined too slowly spam

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/infra#96]
The nodes get a negative chain length change after being restarted. Negative change shouldn't be a reason to raise the` alarm.

**Comment by geigerzaehler** [comment]
We’re also seeing alerts because the network only produces 39 or 38 blocks per hour. The value is due to statistical variation and seems to be acceptable. I’d suggest a threshold of 35 blocks per hour to alert us.

**Comment by geigerzaehler** [comment]
We’re still being alerted for the 10 minute window. There are instance where no block is mined for 10 minutes. This coincides with situations where miners leave the network and the remaining miners are not fast enough. We can see from the graphs that after no block is mined for 10 minutes the difficulty [drops sharply](https://radicle.grafana.net/explore?orgId=1&left=%5B%221588822114090%22,%221588825767766%22,%22grafanacloud-radicle-prom%22,%7B%22expr%22:%22clamp_max(rate(substrate_block_height%20%7B%20kubernetes_cluster%20%3D%20%5C%22ffnet%5C%22,%20status%20%3D%20%5C%22best%5C%22,%20instance%3D%20%5C%22validator-1%5C%22%20%7D%5B10m%5D),%2010)%22,%22hide%22:false,%22interval%22:%22%22,%22legendFormat%22:%22%7B%7B%20instance%20%7D%7D%22,%22datasource%22:%22grafanacloud-radicle-prom%22%7D,%7B%22expr%22:%22substrate_best_block_difficulty%7B%20kubernetes_cluster%20%3D%20%5C%22ffnet%5C%22,%20instance%3D%20%5C%22validator-1%5C%22%20%7D%22,%22hide%22:true%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D). I suggest we increase the window to 11 minutes. There has hasn’t been an incident where this has happened under normal operation.

**Comment by CodeSandwich** [comment]
We don't have the 10 minutes alerts anymore, we're getting alerts from the 7 minutes, but yeah, it's obviously too tight. The alerts are usually going away after few seconds, so increasing it to 8 should be enough.

**Comment by geigerzaehler** [comment]
If you look at [the data](https://radicle.grafana.net/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22grafanacloud-radicle-prom%22,%7B%22expr%22:%22clamp_max(rate(substrate_block_height%20%7B%20kubernetes_cluster%20%3D%20%5C%22ffnet%5C%22,%20status%20%3D%20%5C%22best%5C%22,%20instance%3D%20%5C%22validator-1%5C%22%20%7D%5B8m%5D),%2010)*%208%20*%2060%20%3C%3D%201%22,%22hide%22:false,%22interval%22:%22%22,%22legendFormat%22:%22%7B%7B%20instance%20%7D%7D%22,%22datasource%22:%22grafanacloud-radicle-prom%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) you can see that 8 minutes is not enough either. It would have resulted in four incidents over the last 7 days.
